import type { CardState } from "@/hooks/use-episode-card";

export type Preset = CardState;

export const PRESETS: Preset[] = [
  // TV Series - Episodes 1-26
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:01",
    titleText: "Angel Attack",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:02",
    titleText: "The Beast",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:03",
    titleText: "A Transfer",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:04",
    titleText: "Hedgehog's Dilemma",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:05",
    titleText: "Rei I",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:06",
    titleText: "Rei II",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:07",
    titleText: "The Human Creation",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:08",
    titleText: "Asuka Strikes!",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:09",
    titleText: "Both of You, Dance Like You Want to Win!",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:10",
    titleText: "Magma Diver",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:11",
    titleText: "The Day Tokyo-3 Stood Still",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:12",
    titleText: 'She said, "Don\'t make others suffer\nfor your personal hatred."',
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:13",
    titleText: "Lilliputian Hitcher",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:14",
    titleText: "Weaving a Story",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:15",
    titleText: "Those women longed for the touch\nof others' lips, and thus invited\ntheir kisses.",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:16",
    titleText: "Splitting of the Breast",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:17",
    titleText: "Fourth Child",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:18",
    titleText: "Ambivalence",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:19",
    titleText: "Introjection",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:20",
    titleText: "Weaving a Story 2:\noral stage",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:21",
    titleText: "He was aware that he was\nstill a child.",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:22",
    titleText: "Don't Be.",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:23",
    titleText: "Rei III",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:24",
    titleText: "The Beginning and the End,\nor \"Knockin' on Heaven's Door\"",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:25",
    titleText: "Do you love me?",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  {
    topText: "NEON",
    midText: "GENESIS",
    botText: "EVANGELION",
    epText: "EPISODE:26",
    titleText: "Take care of yourself.",
    titleStyle: "serif",
    titleAlign: "left",
    aspectRatio: "standard",
  },
  // The End of Evangelion
  {
    topText: "",
    midText: "",
    botText: "THE END OF EVANGELION",
    epText: "",
    titleText: "Air",
    titleStyle: "sans",
    titleAlign: "center",
    aspectRatio: "wide",
  },
  {
    topText: "",
    midText: "",
    botText: "THE END OF EVANGELION",
    epText: "",
    titleText: "My purest heart for you",
    titleStyle: "sans",
    titleAlign: "center",
    aspectRatio: "wide",
  },
];

export const TV_EPISODES = PRESETS.slice(0, 26);
export const END_OF_EVANGELION = PRESETS.slice(26);

export function getPresetByEpisode(episodeNumber: number): Preset | undefined {
  return PRESETS.find((preset) => {
    const match = preset.epText.match(/EPISODE:(\d+)/);
    return match && parseInt(match[1]) === episodeNumber;
  });
}

export function getRandomPreset(): Preset {
  return PRESETS[Math.floor(Math.random() * PRESETS.length)];
}
