import type { CardPreset, CardState } from '@vignette/core'

export const twinPeaksPresets: CardPreset[] = [
  {
    id: 'tp01',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 1',
    title: 'Traces to Nowhere',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp02',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 2',
    title: 'Zen, or the Skill to Catch a Killer',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp03',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 3',
    title: 'Rest in Pain',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp04',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 4',
    title: 'The One-Armed Man',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp05',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 5',
    title: "Cooper's Dreams",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp06',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 6',
    title: "Realization Time",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp07',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 7',
    title: "The Last Evening",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp08',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 8',
    title: "May the Giant Be with You",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp09',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 9',
    title: "Coma",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp10',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 10',
    title: "The Man Behind Glass",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp11',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 11',
    title: "Laura's Secret Diary",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp12',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 12',
    title: "The Orchid's Curse",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp13',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 13',
    title: "Demons",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp14',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 14',
    title: "Lonely Souls",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp15',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 15',
    title: "Drive with a Dead Girl",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp16',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 16',
    title: "Arbitrary Law",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp17',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 17',
    title: "Dispute Between Brothers",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp18',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 18',
    title: "Masked Ball",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp19',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 19',
    title: "The Black Widow",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp20',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 20',
    title: "The Path to the Black Lodge",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp21',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 21',
    title: "Miss Twin Peaks",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp22',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 22',
    title: "Beyond Life and Death",
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'standard' },
  },
  {
    id: 'tp23',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 23',
    title: "The Return, Part 1",
    subtitle: 'The Stars Turn and a Time Presents Itself',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'wide' },
  },
  {
    id: 'tp24',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 24',
    title: "The Return, Part 2",
    subtitle: 'The Black Lodge',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'wide' },
  },
  {
    id: 'tp25',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 25',
    title: "The Return, Part 3",
    subtitle: 'Call for Help',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'wide' },
  },
  {
    id: 'tp26',
    headerLines: ['TWIN', 'PEAKS'],
    label: 'EPISODE 26',
    title: "The Return, Part 4",
    subtitle: '...Brings Back Some Memories',
    style: { fontSet: 'gothic', textAlign: 'center', aspectRatio: 'wide' },
  },
]

export const defaultTwinPeaksState: CardState = {
  headerLines: ['TWIN', 'PEAKS'],
  label: 'EPISODE 1',
  title: 'Traces to Nowhere',
  subtitle: undefined,
  style: {
    fontSet: 'gothic',
    textAlign: 'center',
    aspectRatio: 'standard',
  },
  effects: {
    glowEnabled: false,
    glowColor: '#39FF14',
    glowBlur: 15,
    glowOpacity: 0.6,
  },
}
