import type { CardPreset, CardState } from '@vignette-cards/core'

export const evangelionPresets: CardPreset[] = [
  {
    id: 'ep01',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:01',
    title: 'Angel Attack',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep02',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:02',
    title: 'The Beast',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep03',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:03',
    title: 'A Transfer',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep04',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:04',
    title: "Hedgehog's Dilemma",
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep05',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:05',
    title: 'Rei I',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep06',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:06',
    title: 'Rei II',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep07',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:07',
    title: 'The Human Creation',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep08',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:08',
    title: 'Asuka Strikes!',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep09',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:09',
    title: 'Both of You, Dance Like You Want to Win!',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep10',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:10',
    title: 'Magma Diver',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep11',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:11',
    title: 'The Day Tokyo-3 Stood Still',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep12',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:12',
    title: 'She said, "Don\'t make others suffer for your personal hatred."',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep13',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:13',
    title: 'Lilliputian Hitcher',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep14',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:14',
    title: 'Weaving a Story',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep15',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:15',
    title: "Those women longed for the touch of others' lips, and thus invited their kisses.",
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep16',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:16',
    title: 'Splitting of the Breast',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep17',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:17',
    title: 'Fourth Child',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep18',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:18',
    title: 'Ambivalence',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep19',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:19',
    title: 'Introjection',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep20',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:20',
    title: 'Weaving a Story 2: oral stage',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep21',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:21',
    title: 'He was aware that he was still a child.',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep22',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:22',
    title: "Don't Be.",
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep23',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:23',
    title: 'Rei III',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep24',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:24',
    title: 'The Beginning and the End, or "Knockin\' on Heaven\'s Door"',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep25',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:25',
    title: 'Do you love me?',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'ep26',
    headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
    label: 'EPISODE:26',
    title: 'Take care of yourself.',
    style: { fontSet: 'serif', textAlign: 'left', aspectRatio: 'standard' },
  },
  {
    id: 'eoe1',
    headerLines: ['', '', 'THE END OF EVANGELION'],
    label: '',
    title: 'Air',
    style: { fontSet: 'sans', textAlign: 'center', aspectRatio: 'wide' },
  },
  {
    id: 'eoe2',
    headerLines: ['', '', 'THE END OF EVANGELION'],
    label: '',
    title: 'My purest heart for you',
    style: { fontSet: 'sans', textAlign: 'center', aspectRatio: 'wide' },
  },
]

export const defaultEvangelionState: CardState = {
  headerLines: ['NEON', 'GENESIS', 'EVANGELION'],
  label: 'EPISODE:01',
  title: 'Angel Attack',
  subtitle: undefined,
  style: {
    fontSet: 'serif',
    textAlign: 'left',
    aspectRatio: 'standard',
  },
  effects: {
    glowEnabled: false,
    glowColor: '#ffffff',
    glowBlur: 20,
    glowOpacity: 0.8,
  },
}
